guardian/play-googleauth

module/src/main/scala/com/gu/googleauth/model.scala, module/version.sbt
Backports https://github.com/guardian/play-googleauth/commit/1d28a8dd13927934c11d0ea19df033df7e5bc705 for the Play 2.2.x branch
=> Fix google auth response

module/build.sbt, module/src/main/scala/com/gu/googleauth/groups.scala
Google have discontinued the Provisioning API the GoogleGroupChecker used to work out which Google Groups the user is in - the Directory API is the replacement.
Implementation is taken from https://github.com/guardian/membership-frontend/pull/496
cc @dominickendrick
=> Replace GoogleGroupChecker implementation with the Directory API

module/build.sbt, module/version.sbt
Now that Play 2.4 is out, make that master (I've pushed up a play-2.3.x branch). 
Note that Play 2.4 requires Java 8, so laggards will need to get on that bandwagon to use it.
=> Play 2.4 final

README.md
Based on the work we have recently done to use the Directory API with play-googleauth in https://github.com/guardian/identity-admin/ 
It comes as an addition to the doc present in https://github.com/guardian/play-googleauth/blob/master/module/src/main/scala/com/gu/googleauth/groups.scala
@markjamesbutler it would be good to have your opinion on this
@rtyley @jennysivapalan would you mind having a look since you both worked on the groups module?
Thanks
=> Add documentation for the Directory API

module/src/main/scala/com/gu/googleauth/auth.scala, module/version.sbt
OpenID Connect allows an additional parameter "prompt" to be set on authentication requests.  This specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
Supported values include, none, consent, login, select_account.
(http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
=> Add prompt to authentication request

example/app/controllers/Application.scala, example/app/controllers/Login.scala, example/app/views/index.scala.html, example/build.sbt, example/conf/routes, module/src/main/scala/com/gu/googleauth/actions.scala
I've included an updated example to show how to use the filter, this is the core bit:
```
type GoogleAuthRequest[A] = AuthenticatedRequest[A, googleauth.UserIdentity]
def authenticatedAndInGroup = (AuthAction andThen requireGroup[GoogleAuthRequest](includedGroups = Set("membership.dev@guardian.co.uk"))) {
request => Ok(views.html.authenticated(request))
}
```
Note that I _haven't_ configured an example `GoogleServiceAccount`, as those credentials would allow anyone to read Guardian Google Group membership!
This code is taken from membership-frontend, where we quite often have a request type which isn't just a `AuthenticatedRequest[A, googleauth.UserIdentity]` (for instance, it might contain Membership data!)- so I've had to do a bit of refactoring (introducing `UserIdentifier`) so that …
=> Add a 'requireGroup' filter that checks Google Group membership

module/build.sbt, module/project/Dependencies.scala
The google-api-services-admin-directory artifact has a transitive dependency on com.google.guava:guava-jdk5 - a nasty artifact that clashes with the regular com.google.guava:guava artifact, providing two versions of the same classes on your classpath! To prevent problems, we specifically exclude this evil artifact, and ensure we have regular guava available.
See also:
https://github.com/guardian/subscriptions-frontend/pull/363#issuecomment-186190081
http://stackoverflow.com/questions/25792398/gradle-transitive-dependency-exclusion-is-not-working-as-expected-how-do-i-get
cc @cb372 @rrees
=> Fix awful guava-jdk5 dependency introduced by Google Directory API client

example/app/auth/AuthActions.scala, example/build.sbt, module/src/main/scala/com/gu/googleauth/auth.scala
The domain parameter is used to restrict logins to a specific email domain, rather than allowing any google mail account. It's very easy to forget to include this option or to have it be accidentally removed without anyone noticing.
This change removes the GoogleAuthConfig constructor and provides two different methods for creating instances. The default method (`apply`) now explicitly requires a domain. An alternative is provided that does not require a domain and it is named to make it very clear that this will not include domain protection.
While this is a "general-purpose" library in practice the only users are at the Guardian. Our applications all need to enforce a Guardian email check and this makes writing correct code the path of least resistance.
I think `5.3` should be the next …
=> Make it much harder to accidentally fail to provide an email domain

README.md
I decided that the source incompatibility due to the changes in Cats meant it was worth a bigger version bump.
=> Specify 0.6.0, not 0.5.3 in README

README.md
Update the README to use the correct scope, i.e. the one that the client actually requests. This cost me an hour or two...
See https://github.com/guardian/play-googleauth/blob/3c008356055c9b80b2a69e6c40f19af4eb9a31e2/module/src/main/scala/com/gu/googleauth/groups.scala#L53
@adamnfish @philwills 👋
=> Fix scope name in readme

module/build.sbt
Just like #48 but for the `play-2.5.x` branch since I'm doing this for [bolt](https://github.com/guardian/bolt) which is on Play 2.5
=> Upgrade cats to 1.0.1 for Play 2.5.x

module/build.sbt
Since #50, `sbt release` doesn't actually work, I *think* because the newer version of `sbt-sonatype` needs a `publishTo` parameter.
Of course, just as with the changes in #50, I can't actually test it without merging this to master, since `sbt-release` wisely doesn't let you release if you have unstaged modified files or if local is out of sync with remote
@adamnfish if you have any suggestions for ways to test things like this before creating the PR, I'm all ears!
=> Add publishTo parameter for sbt-sonatype plugin

module/build.sbt
Since #51, `sbt release` doesn't actually work, I *think* because the newer version of `sbt-sonatype` needs a `publishTo` parameter.
Of course, just as with the changes in #51, I can't actually test it without merging this to master, since `sbt-release` wisely doesn't let you release if you have unstaged modified files or if local is out of sync with remote
=> Add publishTo parameter for sbt-sonatype plugin (Play 2.5.x)

example/build.sbt, example/project/build.properties, example/project/plugins.sbt, module/build.sbt, module/project/Dependencies.scala, module/project/build.properties
Snyk just alerted us on the @guardian/ophan team to an 'Arbitrary Command Execution' vulnerability in `org.mortbay.jetty:jetty`:
https://snyk.io/vuln/SNYK-JAVA-ORGMORTBAYJETTY-32091
...introduced through:
```
com.google.gdata:core@1.47.1 ›
com.google.oauth-client:google-oauth-client-jetty@1.11.0-beta ›
org.mortbay.jetty:jetty@6.1.26
```
The `com.google.gdata:core` library was introduced to `play-googleauth` with #20 in December 2014, but it became superfluous in April 2015 with #23. We can just remove it!
Note that the vulnerability probably wouldn't have actually affected us, because we weren't actually *running* Jetty, but in any case this is getting rid of noise.
Updating to Play 2.6.15 also gets us the less vulnerable version of `jackson-databind`:
* …
=> Remove obsolete `com.google.gdata:core` library, and bump Play version

README.md
The proper/latest version number is indicated by the maven widget. This will prevent people importing an obsolete version number.
=> Update README.md with more generic better version

build.sbt, src/main/scala/com/gu/googleauth/auth.scala, src/test/scala/com/gu/googleauth/AntiForgeryCheckerTest.scala
`play-secret-rotation` v0.15 supports both Play 2.6 & 2.7 thanks to https://github.com/guardian/play-secret-rotation/pull/8
In order to use `play-secret-rotation` v0.15 in a project that also uses `play-googleauth`, `play-googleauth` needs to be built against that version of `play-secret-rotation` too (due to binary-incompatible case class changes).
=> Update to latest version of `play-secret-rotation`, drop Scala v2.11

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
This project compiles with Scala 2.12 by default, but now additionally can cross-compile to Scala 2.13 for the versions of Play that support it (ie Play 2.7, but not Play 2.6).
* `cats-core` & `scalatest` both updated to cross-compiled versions
* `play-secret-rotation` updated to cross-compiled version https://github.com/guardian/play-secret-rotation/pull/9
=> Add Scala 2.13 support everywhere we can (ie Play 2.7, but not Play 2.6)

build.sbt, play-v26/src/main/scala/com/gu/googleauth/auth.scala, play-v26/src/test/scala/com/gu/googleauth/GoogleAuthTest.scala, project/Dependencies.scala
Hi :wave: 
We're using this library to control access to an app but now we have people on multiple G-Suite domains and currently we can't give everyone access as only one domain can be set, as such this PR just switches the `Option[String]` domain parameter to be a `List[String]`
~~I haven't (yet!) been able to run this locally but I'm going to try today and I thought I'd open this PR in advance.~~
=> Support restricting auth to more than one domain

project/Dependencies.scala, project/plugins.sbt
This change is a dependency update. It updates the following three modules:
- `google-api-services-admin-directory`
- `google-api-client` 
- `commons-codec` 
Module`google-oauth-client` versions up to 1.30.x are affected by a high-severity security vulnerability (see [Snyk report](https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276)).
The current change updates module `google-api-services-admin-directory` that has a transitive dependency through `google-api-client` on one of these vulnerable versions.
A higher version of `google-api-client` than the one picked up by `google-api-services-admin-directory` is specified explicitly as it fixes the issue https://github.com/googleapis/google-api-java-client/issues/1487.
The `commons-codec` module is additionally updated to resolve …
=> Update google-oauth-client to v1.31.0

README.md, version.sbt
Since PR #79 was merged and [published](https://search.maven.org/artifact/com.gu.play-googleauth/play-v28_2.13/2.0.0/jar), we should link to the latest versions of this library on Maven.
=> Update readme with latest versions

build.sbt
The Play framework is [_really particular_](https://www.playframework.com/documentation/2.8.x/ScalaAkka#Updating-Akka-version) about the versions of Akka and Akka HTTP that it uses - unless you're directly using Akka HTTP, it's best to avoid explicitly adding Akka HTTP as a dependency (even a transitive one) on a Play project, because it's quite likely you'll choose a different version to Play, and [mixed versions aren't allowed](https://doc.akka.io/docs/akka/2.6/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed).
In the case of PR https://github.com/guardian/play-googleauth/pull/79, which added `akka-http` as a runtime dependency of `play-googleauth`, the dependency caused `ClassNotFoundException`s at runtime in Ophan when we upgraded to the latest version of …
=> Don't pass on akka-http as an explicit-runtime dependency, avoid ClassNotFoundExceptions

play-v27/src/main/scala/com/gu/googleauth/groups.scala, project/Dependencies.scala
Snyk rates this as a high-severity issue: https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276
> Remediation
> Upgrade com.google.oauth-client:google-oauth-client to version **1.31.0** or higher.
Note that, slightly confusingly, we had a [prior PR](https://github.com/guardian/play-googleauth/pull/77) in `play-googleauth` titled "Update google-oauth-client to v1.31.0", but the title was at odds with the actual change in that PR (easy to do!), which only updated the library to v1.30.10:
https://github.com/guardian/play-googleauth/blob/f8422fed4f244f13a653d1f98ecbf2cd538d2ebc/project/Dependencies.scala#L48
As far as SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276 goes, the commit for that was https://github.com/googleapis/google-oauth-java-client/commit/13433cd7, which indeed was only …
=> Fix SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276, update google-api-client

README.md, build.sbt, play-v27/src/main/scala/com/gu/googleauth/groups.scala, project/Dependencies.scala, version.sbt
This change is only related to the Google-Group-checking code in `play-googleauth`, which was using a deprecated class:
The `com.google.api.client.googleapis.auth.oauth2.GoogleCredential` class in https://github.com/googleapis/google-api-java-client was deprecated in May 2019 by https://github.com/googleapis/google-api-java-client/pull/1258 ...the deprecation advice recommends using the classes from the new library: https://github.com/googleapis/google-auth-library-java
This commit switches to using the new `com.google.auth.oauth2.ServiceAccountCredentials` class from the
`google-auth-library-oauth2-http` artifact. Given this new class, our custom `com.gu.googleauth.GoogleServiceAccount` Scala case class is no longer necessary and I've removed it, in favour of the user passing us an …
=> Remove use of deprecated `GoogleCredential` class

README.md
The link to the example code in the readme was pointing to `play-v26` which doesn't seem to exist anymore
=> update broken link in the readme

build.sbt, project/Dependencies.scala, project/build.properties, project/plugins.sbt
This PR aims to batch up the various Scala Steward dependency updates in the project: 
Some these versions were causing an issue in Ophan: 
```
Caused by: java.lang.IllegalStateException: You are currently running with version 2.1.2 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Admin SDK API library.
```
Can we do a beta release of this change to confirm it works in other repos i.e. Ophan? 
The project is using the latest dependency versions.
=> Bump various dependencies

sonatype.sbt
I noticed that following the link from maven you end up in the wrong repo, not sure if it was intentional but it would make sense to me that this would point to here ?
In case it's wrong I'm not sure if it's worth having a release for that but maybe have it fixed for the next one.
I guess the url for this repo would show when searching this library in the places like the maven repo?
=> wrong repo url in sonatype.sbt?

build.sbt, play-v27/src/main/scala/com/gu/googleauth/auth.scala, play-v27/src/main/scala/com/gu/googleauth/groups.scala, play-v27/src/main/scala/com/gu/googleauth/model.scala, play-v27/src/sbt-test/example/webapp/app/AppComponents.scala, play-v27/src/sbt-test/example/webapp/app/views/authenticated.scala.html, play-v27/src/test/scala/com/gu/googleauth/AntiForgeryCheckerTest.scala, project/Dependencies.scala, project/build.properties, version.sbt
This is in preparation for adding the support for Play 2.9 & 3, as well as Scala 3, in PR https://github.com/guardian/play-googleauth/pull/200.
Joda-Time is dropped from the latest versions of Play, so we either would have had to specifically add it, or just move over to `java.time` which is the right thing to do! This does mean that the signature of `GoogleAuthConfig`, and some of its constructor methods changes - the `maxAuthAge` field is no longer a `org.joda.time.Duration`, it's now a `java.time.Duration`, which may require some minor code changes in calling code - for instance [in Amigo](https://github.com/guardian/amigo/blob/a0ae7156a367b297698559fc7da99fcf2f39f007/app/components/AppComponents.scala#L276).
=> Drop Scala 2.12, drop Joda-Time - `maxAuthAge` becomes a `java.time.Duration`

build.sbt, play-v27/src/main/scala/com/gu/googleauth/TwoFactorAuthChecker.scala, play-v27/src/main/scala/com/gu/googleauth/actions.scala, play-v27/src/main/scala/com/gu/googleauth/auth.scala, play-v27/src/main/scala/com/gu/googleauth/groups.scala, play-v27/src/test/scala/com/gu/googleauth/TwoFactorAuthCheckerCLITester.scala
Checking users have 2FA enabled before they access internal Guardian tools is very important (good security practice, required by GDPR, etc), but in the past it's not been possible to directly check if a user has 2FA enabled - as a proxy, we've checked the user for membership of the `2fa_enforce@guardian.co.uk` Google Group. The Google Group was manually administered, so suffered from reconciliation issues, and Patrick Simkins reports the group does not correspond well with our onboarding process.
Recently, in discussion about this, @andrew-nowak pointed out that we can use Google's Admin SDK Directory API and retrieve the Directory API [`User`](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users#resource:-user) entity, giving access to the `isEnrolledIn2Sv` field …
=> Support requiring 2FA for authentication, check `isEnrolledIn2Sv`

.scala-steward.conf
Looking at Scala Steward PR https://github.com/guardian/play-googleauth/pull/199, we can see that Scala Steward is [trying to upgrade Play version numbers](https://github.com/guardian/play-googleauth/pull/199/files#r1419066470) in ways that [aren't correct](https://www.playframework.com/documentation/3.0.x/Migration30#Changed-groupId).
This is possibly related to https://github.com/scala-steward-org/scala-steward/pull/3191 & https://github.com/scala-steward-org/scala-steward/pull/3191#discussion_r1395531926
To fix this up, for now we'll ignore Play updates here, as in https://github.com/guardian/play-secret-rotation/commit/607802e387b082de605a27b2097d1e1efd92d3a5
=> Prevent Scala Steward breaking com.typesafe.play

play-v27/src/main/scala/com/gu/googleauth/model.scala
It seems that sometimes Google does not return this field, which is preventing users from logging in.
=> Make Locale optional

build.sbt
This updates our version of `play-secret-rotation` to the version that fixes https://github.com/guardian/play-secret-rotation/issues/445 with PR https://github.com/guardian/play-secret-rotation/pull/446.
Re-releasing `play-googleauth` with this update is probably not essential - it looks like the already-released version v6.0.0 of `play-googleauth` works just fine with it, they are not binary-incompatible - but I guess it's nice to have them all compiled against the nicest version of the code.
=> Update play-secret-rotation with CSRF fix

play-v29/src/main/scala/com/gu/googleauth/actions.scala
I noticed that we were getting a deserialisation error displayed in the UI.  This is not security best practice to output arbitrary exception information:
[Improper handling of errors can introduce a variety of security problems for a web site. The most common problem is when detailed internal error messages such as stack traces, database dumps, and error codes are displayed to the user (hacker). These messages reveal implementation details that should never be revealed. Such details can provide hackers important clues on potential flaws in the site and such messages are also disturbing to normal users.](https://owasp.org/www-community/Improper_Error_Handling#:~:text=The%20most%20common,to%20normal%20users.)
=> don't reveal internal error details via UI

play-v29/src/main/scala/com/gu/googleauth/actions.scala
This follows on from https://github.com/guardian/play-googleauth/pull/233 - it turns out the `message` val is now unused, so we can remove it, and simplify the code a little!
PR #233 removed the exception message text from the error displayed to the end user, because the error message text is unconstrained and this corresponds to https://owasp.org/www-community/Improper_Error_Handling .
I was tempted to re-include the `desc` string in the error message displayed to the user, as it is just the string "anti-forgery-token-invalid" or the exception class name, which is more constrained, but re-reading the OWASP doc, this is also discouraged as it's very similar to an error code. (_"internal error messages such as stack traces, database dumps, and error codes"_). When getting error reports in …
=> Remove unused `message` val

build.sbt
See here more info: https://github.com/guardian/gha-scala-library-release-workflow/issues/33
=> Temporarily disable compatibility testing as last release failed

build.sbt
Reverts guardian/play-googleauth#235
=> Revert "Temporarily disable compatibility testing as last release failed"

build.sbt
Co-authored-by: @rtyley
brings in the release https://github.com/guardian/play-secret-rotation/releases/tag/v8.4.5
=> bump to newly released play-secret-rotation

play-v29/src/sbt-test/example/webapp/project/build.properties, project/build.properties
* Bumping sbt to the latest version
* We're now using a symbolic link for the sbt version of the subprojects
sbt 1.1.6 isn't recent enough for Snyk: https://chat.google.com/room/AAAAag0I08g/fFGcXFskQKk/7O5BVztqn3w?cls=12. We expect this to fix this job: https://github.com/guardian/play-googleauth/actions/runs/9891177854
=> Bump sbt version to 1.10.1

play-v29/src/main/scala/com/gu/googleauth/auth.scala, play-v29/src/test/scala/com/gu/googleauth/AntiForgeryCheckerTest.scala
[`jjwt`](https://github.com/jwtk/jjwt) is a library for creating and verifying [JSON Web Tokens](https://jwt.io/introduction) (JWTs), which we've used directly in `play-googleauth` for the `AntiForgeryChecker` since PR https://github.com/guardian/play-googleauth/pull/52 in January 2018.
* `signWith()` & `setSigningKey()` now prefer to be given a `Key` type rather than a base64-encoded String - deprecated in https://github.com/jwtk/jjwt/pull/341
* To obtain a configured `JwtParser`, a builder is now preferred, ie `Jwts.parserBuilder().setSigningKey(key).build()` rather than `Jwts.parser().setSigningKey(key)` - deprecated in https://github.com/jwtk/jjwt/pull/486
* Use `io.jsonwebtoken.security.SignatureException` rather than `io.jsonwebtoken.SignatureException` - deprecated in …
=> Avoid deprecated `jjwt` methods for signing & parsing

.github/workflows/ci.yml, play-v29/src/sbt-test/example/webapp/app/AppComponents.scala, play-v29/src/sbt-test/example/webapp/app/controllers/Application.scala, play-v29/src/sbt-test/example/webapp/app/controllers/Login.scala, play-v29/src/sbt-test/example/webapp/app/views/authenticated.scala.html, play-v29/src/sbt-test/example/webapp/app/views/index.scala.html, play-v29/src/sbt-test/example/webapp/app/views/login.scala.html, play-v29/src/sbt-test/example/webapp/build.sbt, play-v29/src/sbt-test/example/webapp/project/plugins.sbt, play-v29/src/sbt-test/example/webapp/version.sbt
We've updated the example app, as part of an effort to see if we could get Snyk to work again (Snyk was attempting to build the inner example app, not just the top-level project) - but Snyk will probably continue to fail, as the inner example app depends on a snapshot release of play-googleauth that needs to be locally published.
We're going to switch to GHAS with https://github.com/guardian/play-googleauth/pull/243 anyway, so will take the example app fixes, but not worry too much about Snyk being broke.
=> Upgrade example app to work with latest versions

.github/workflows/ci.yml
See more at: https://github.com/guardian/redirect-resolver/pull/24
Observe CI on this PR
CI should run successfully
=> Fix failing CI due to sbt not found error

.github/workflows/sbt-dependency-graph.yaml
The sbt-dependency-graph workflow has started failing, because it uses ubuntu-latest but doesn’t install Java or sbt: since github have updated ubuntu-latest to point to ubuntu-24.04, it has less software pre-installed by default.
The updates come from copying the version in
https://github.com/guardian/content-api-transformer-lambda/pull/95, which was raised by the bot recently and has been updated to install the necessary dependencies.
We could alter the triggers for the workflow to let it run on this branch in order to test it, but since it's working correctly on content-api-transformer-lambda already, I'm tempted to just merge and see.
=> Install Java and sbt in dependency-graph workflow

play-v29/src/main/scala/com/gu/googleauth/groups.scala
The `GoogleGroupChecker` class makes requests to the Google directory service to find each user's groups.
Currently if the `requireGroup` Filter is used to check group memberships, a request is made to the Google API every time. I have found that these requests can take ~600ms each time, which can really add up if a webapp needs to make multiple requests, or if the `requireGroup` Filter is chained.
This PR introduces a cache to the `GoogleGroupChecker` class to reduce the number of calls to the Google directory. The cache duration is now a class parameter, and defaults to 1 minute.
Note - I've used Google's guava cache here because it's already available in this library.
=> Cache results of group checker

version.sbt
This release failed https://github.com/guardian/play-googleauth/actions/runs/14858933594
which caused subsequent ones to fail with an error determining the version.
This PR reverts the version change so that we can try releasing v24 again.
I have also deleted the "release" and "tag" using GH ui.
=> revert back to v23 so that we can retry the failed release

build.sbt, project/Dependencies.scala
Fixing https://github.com/guardian/play-googleauth/security/dependabot/12.
GHSA-h46c-h94j-95f3
CVE-2025-52999
There's no version of Play that is compiled against Jackson 2.15 - we would need to wait for Play 3.1 for that.
After discussion with DevX, we've confirmed that our policy that we treat labelling of repositories as 'production' the same whether they are app repos or library repos - so long as the code runs in Production at the Guardian, it should be labelled 'production', and have the same SLAs.
=> CVE-2025-52999: Force Play to use a newer version of Jackson

project/Dependencies.scala
This library’s dependencies on play were marked as using [Provided scope](https://www.baeldung.com/maven-dependency-scopes#2-provided), which seems to have interacted poorly with our dependency vulnerability tracking. Even though we recently [added an override to avoid a jackson vulnerability](https://github.com/guardian/play-googleauth/pull/308), the older version of jackson was still reported by the sbt-dependency-graph workflow to the dependency graph on github. (Meaning the project incorrectly (we think) continued to show as vulnerable on our vulnerability dashboard.)
This commit changes these to the default Compile scope, which should let our dashboard show us what we expect. It will have a slightly different behaviour for consumers of the library, where this library’s dependency on …
=> Change play dependencies to Compile scope

project/plugins.sbt
With the update to `gha-scala-library-release-workflow` v2 made by dependabot:
* https://github.com/guardian/play-googleauth/pull/312
...we can remove the `sbt-sonatype` plugin, thanks to:
* https://github.com/guardian/gha-scala-library-release-workflow/pull/62
...it's a shame we can't get dependabot to automate this with its PRs!
=> Remove sbt-sonatype plugin
