module/src/main/scala/com/gu/googleauth/auth.scala
If you're using Play 2.4 with compile-time DI, it's a little tricky to use play-googleauth in its current state because it depends on extracting the WS client from the currently running app. This means:
* you need to import `Play.current`, which is frowned upon in Play 2.4
* you have to add the WS components to the application's injector
Added some overloads that allow you to pass a WS client (or rather a `WSAPI`, to be precise) explicitly, which avoids this mess.
Ideally `GoogleAuth` should be an injectable component, not an `object`, but I'm going with this easier fix for now.
=> Add some Play 2.4-friendly overloads

README.md
Easy to forget to update the README
=> Include a badge for the latest version

module/src/main/scala/com/gu/googleauth/auth.scala
Ported from 7a956bec14e043081a9c952be9492afc3a7598ee for Play 2.3.x
=> Enforce domain verfication if supplied in config

example/build.sbt, example/conf/application.conf, example/project/build.properties, example/project/plugins.sbt
Verified that I could still get to http://localhost:9000/authenticated - it worked!
cc @sihil
=> Update example to use Play 2.4

module/build.sbt, module/project/build.properties, module/project/plugins.sbt
I had to download SBT 0.13.5 to compile this project! This will not stand!
cc @sihil
=> Bump SBT & SBT plugin versions

module/build.sbt, module/src/main/scala/com/gu/googleauth/actions.scala
and Scala to 2.11.8
@philwills @sihil
=> Upgrade Cats to 0.7.0

README.md, module/build.sbt, module/src/main/scala/com/gu/googleauth/actions.scala, module/version.sbt
@adamnfish @philwills current version of `cats` used by `play-googleauth` is incompatible with the latest version of `cats` (`0.8.1`)
=> bumped cats version to 0.8.1

module/build.sbt
Same old story as #44, #42, etc
=> Upgrade cats to 1.0.1

module/project/plugins.sbt
Having problems releasing - I suspect this may fix it
=> Upgrade sbt plugins for Play 2.5

module/project/plugins.sbt
Having problems releasing - I suspect this may fix it
=> Upgrade sbt plugins

README.md
@rtyley, you can let me know if this sort of detail is overkill - since everyone seems to be having binary compatibility issues with cats at the moment, I thought it was worth being explicit
=> Update README.md with cats version info

module/src/main/scala/com/gu/googleauth/actions.scala
This PR follows on from https://github.com/guardian/play-googleauth/pull/52 which introduced JWT signing of the anti-forgery token (with an aggressive timeout of 60 seconds - we arbitrarily chose that timeout as an expiration time to guard against malicious re-use).
If a user was sent off to the Google auth flow, but took longer than 60 seconds to complete that flow (maybe they were asked a password, or just asked to select from multiple Google accounts that they possessed), their JWT anti-forgery token would have expired, and the user would receive an unfriendly "JWT Expired" message:
This change means that instead of seeing that message, they will instead be taken directly back to Google to re-authenticate (if they were asked their password before, it's likely Google won't ask them …
=> Send users with expired JWT tokens back to the start of the OAuth flow

example/project/build.properties, example/project/plugins.sbt, module/project/build.properties, module/project/plugins.sbt
Needed for newer 18.04 Ubuntu boxes!
https://stackoverflow.com/questions/44317384/sbt-error-failed-to-construct-terminal-falling-back-to-unsupported
https://github.com/sbt/sbt/issues/3240
=> Update to sbt 1.1.5

project/build.properties, project/plugins.sbt
This version of sbt is exciting because it uses Coursier for faster dependency resolution!
https://www.lightbend.com/blog/sbt-1.3.0-release
=> Update to sbt v1.3

play-v26/src/main/scala/com/gu/googleauth/auth.scala
On Ophan, we've been receiving a few reports recently from users who can't access Dashboard due to Anti-forgery token invalid errors. We're tracking this in https://github.com/guardian/ophan/issues/3686.
It would be useful to have some more logging to help us debug the problem, so we're adding it here.
=> Add logging to debug problems with session id

README.md
as part of making "main" the default branch (words matter), I have fixed the readme link
https://docs.google.com/document/d/1nqC5Uk6n3y7S79m1yiG6oqT8NtXWpDcsS-uLI_RK7Mg/edit#heading=h.1jefiiboz7qc
=> fix link to reflect new branch name

.gitignore, build.sbt, project/build.properties, project/plugins.sbt
=> Bump version of sbt, it's plugins, and play-secret-rotation

project/Dependencies.scala
https://cloud.google.com/java/docs/bom#guava_versions_-jre_or_-android
=> Fix Google APIs trying to pull in Android versions of Guava

.scala-steward.conf, build.sbt
See https://github.com/guardian/play-secret-rotation/issues/449
=> Revert to unbroken play-secret-rotation

.github/dependabot.yml
We'd like to see updates to v2 rolling out!
=> Add dependabot for the release workflow
